import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSelector, useDispatch } from "react-redux";
import { decrement, increment, selectValue } from "../slices/counterSlice";

export default function Home() {
  const count = useSelector(selectValue);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Counter App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>The value of counter is {count}.</h1>
        <div className={styles.div}>
          <button onClick={() => dispatch(increment())}>Increment</button>
        </div>
        <div className={styles.div}>
          <button onClick={() => dispatch(decrement())}>Decrement</button>
        </div>
      </main>
    </>
  );
}
